# Generated by Django 3.1.4 on 2023-07-11 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20230706_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter1',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter2',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter3',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter4',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter5',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(30.0)]),
        ),
    ]
