# Generated by Django 3.1.4 on 2023-08-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
